# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/Android
    branches:
      only:
        - master
        - /feature-.*/
        - /bug-.*/
        - develop
        - /hotfix-.*/
    docker:
      - image: circleci/android:api-28-ndk-r17b
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    steps:
      - checkout
      - attach_workspace:
          at: ~/Android/AppsterAndroid/Appster
      - restore_cache:
          pwd: AppsterAndroid/Appster
          key: jars-{{ checksum "AppsterAndroid/Appster/build.gradle" }}-{{ checksum  "AppsterAndroid/Appster/app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          pwd: AppsterAndroid/Appster
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          pwd: AppsterAndroid/Appster
          paths:
            - ~/.gradle
          key: jars-{{ checksum "AppsterAndroid/Appster/build.gradle" }}-{{ checksum  "AppsterAndroid/Appster/app/build.gradle" }}
      - run:
          pwd: AppsterAndroid/Appster
          name: Run Tests
          command: ./gradlew lintDebug
      - run:
          pwd: AppsterAndroid/Appster
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
